### ISSUE TITLE
mini dokumentacja by sie przydala

### ISSUE THREAD

**Issue by dilotec-2015** [nSolutionsPL/filmweb-api#3]
dzieki za api - smiga bez problemu...
przydaloby sie troche udokumentowac jak tego uzywac :-)
w koncu rozkminilem o co chodzi, ale zajelo mi to chwile ;-)

mam jednak dwa pytania:
1. getFilmPersons - jakie argumenty trzeba podac jako 'type'? nijak nie moge zgadnac...
2. jak wyszukiwac film znajac tylko tytul? teraz trzeba znac filmId

**Comment by Nicramus** [comment]
@dilotec-2015 
Hej czy to API wciąż działa?
Odpaliłem test.php i mam coś takiego

Fatal error: Uncaught Exception: Nie otrzymano odpowiedzi in D:\PROJEKTY\PHP\www\filmweb-api\tests\Filmweb\nSolutions\Request.php:43 Stack trace: #0 D:\PROJEKTY\PHP\www\filmweb-api\tests\Filmweb\nSolutions\API\Methods.php(107): nSolutions\Request::execute(Array, Array) #1 D:\PROJEKTY\PHP\www\filmweb-api\tests\Filmweb\nSolutions\API\Methods.php(38): nSolutions\API\Methods->_process() #2 D:\PROJEKTY\PHP\www\filmweb-api\tests\test.php(36): nSolutions\API\Methods->execute() #3 {main} thrown in D:\PROJEKTY\PHP\www\filmweb-api\tests\Filmweb\nSolutions\Request.php on line 43

**Comment by b44x** [comment]
Minęły ponad dwa lata - i jestem w stanie odpisać!
Przepraszam, że tak późno.

Niedługo mam zamiar się zająć ponownie projektem oraz lekko ulepszyć, a na pewno uzupełnić dokumentację.
